version: 2.1
jobs:
  build:
    docker:
      - image: docker:19.03.8-git
        user: root
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.8
      - add_ssh_keys:
          fingerprints:
            - "c6:f0:85:c6:72:8d:5e:3d:05:24:25:3c:d0:24:81:d9"

      # build and push Docker image then deploy on remote
      - run:
          name: build and push release to registery
          command: |
            TAG=0.$CIRCLE_BUILD_NUM
            echo "$GitHub_action_password" | docker login docker.pkg.github.com -u $GitHub_login --password-stdin
            docker build -t docker.pkg.github.com/patrick-ivann/rapide-shortener/production:$TAG -f dockerfile --network=host --build-arg RapideShortener_Kestrel__EndpointDefaults__Protocols=$RapideShortener_Kestrel__EndpointDefaults__Protocols --build-arg RapideShortener_URLDatabaseSettings__ConnectionString=$RapideShortener_URLDatabaseSettings__ConnectionString --build-arg RapideShortener_URLDatabaseSettings__DatabaseName=$RapideShortener_URLDatabaseSettings__DatabaseName --build-arg RapideShortener_URLDatabaseSettings__UrlCollectionName=$RapideShortener_URLDatabaseSettings__UrlCollectionName .
            docker push docker.pkg.github.com/patrick-ivann/rapide-shortener/production:$TAG
      - run:
          name: Deploy app to AWS EC2 Server via Docker
          command: |
            argument=0.$CIRCLE_BUILD_NUM
            ssh -o StrictHostKeyChecking=no circle@$ec2Squeat "~/scripts/deploy_rapideShortenerNetBack_app.sh docker.pkg.github.com/patrick-ivann/rapide-shortener/production:$argument > ./remote_result/log_$argument.txt"
workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - develop
                - master
