apiVersion: v1
kind: Service
metadata:
  labels:
    app: ${APP_NAME}
  name: ${APP_NAME}
  namespace: ${NAMESPACE}
spec:
  ports:
  - port: 5001
    name: grpc
    protocol: TCP
    targetPort: 5001
  - port: 3333
    name: web
    protocol: TCP
    targetPort: 3333
  selector:
    app: ${APP_NAME}
  type: ClusterIP