name: build and deploy production
on:
  push:
    branches:
      - production
jobs:
  build:
    if: |
        contains(github.event.head_commit.message, ':rocket:') ||
        contains(github.event.head_commit.message, '🚀')
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2

      - name: reset tag 
        run: echo 'SHORTENED_TAG='$(git log -1 --pretty=%h) >> $GITHUB_ENV
        
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Print environment variables exposed by GitHub
        run: |
          echo "GITHUB_ACCESTOKEN=${{ secrets.PA_TOKEN }}"
          echo "GHCR=${{ secrets.GHCR_LOGIN }}"

      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_LOGIN }}
          password: ${{ secrets.PA_TOKEN }}
      -
        name: Build and push
        env:
          PROTOCOLS: "Http2" 
          CONNECTION_STRING: "mongodb+srv://rapide-julien:J7lwunpO6Q056Fil@mongodb-rapide-cluster-hehrd.mongodb.net/test?authSource=admin&replicaSet=mongodb-rapide-cluster-shard-0&readPreference=primary&appname=MongoDB%20Compass%20Community%20Beta&ssl=true"
          DATABASE_NAME: rapide
          URL_COLLECTION_NAME: urls
        if: contains(github.event.head_commit.message, ':rocket:')
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: "ghcr.io/patrick-ivann/rapide-shortener:${{github.sha}}"
          build-args: |
            RapideShortener_Kestrel__EndpointDefaults__Protocols=${{ env.PROTOCOLS }}
            RapideShortener_URLDatabaseSettings__ConnectionString=${{ env.CONNECTION_STRING }}
            RapideShortener_URLDatabaseSettings__DatabaseName=${{ env.DATABASE_NAME }}
            RapideShortener_URLDatabaseSettings__UrlCollectionName=${{ env.URL_COLLECTION_NAME }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: |
        contains(github.event.head_commit.message, ':rocket:') ||
        contains(github.event.head_commit.message, '🚀')

    env:
      APP_NAME: rapide-shortener-grpc
      NAMESPACE: production
      IMAGE: ghcr.io/patrick-ivann/rapide-shortener
      IMAGE_TAG: ${{github.sha}}
      FULL_DOMAIN: share.lunaar.net
      FULL_DOMAIN_GRPC: shortener.lunaar.net

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: reset tag 
        run: echo 'SHORTENED_TAG='$(git log -1 --pretty=%h) >> $GITHUB_ENV
        
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Save DigitalOcean kubeconfig
        run: doctl kubernetes cluster kubeconfig save $CLUSTER_NAME
        env: 
          CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}
    
      - name: Save DigitalOcean kubeconfig
        run: doctl kubernetes cluster kubeconfig save $CLUSTER_NAME
        env: 
          CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}

      - name: Deploy to Kubernetes - populate and apply deployment 
        run: |
          cat ./K8S/Deployment.yaml | envsubst | kubectl apply -f -

      - name: Deploy to Kubernetes - populate and apply service 
        run: |
          cat ./K8S/Service.yaml | envsubst | kubectl apply -f -

      - name: Deploy to Kubernetes - populate and apply routing 
        run: |
          cat ./K8S/Ingress.yaml | envsubst | kubectl apply -f -

      - name: Verify deployment
        run: kubectl rollout status deployment/${APP_NAME} -n ${NAMESPACE}